name: Rust

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh 

      - name: make dir
        run: mkdir app
      - name: copy
        run: mv ./target/release/axum-deom ./app/axum

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "standard-rust-axum-api"
          heroku_email: "romainharvier@gmail.com"
          appdir: "./app"
          procfile: "web: ./axum"
          buildpack: "https://github.com/ph3nx/heroku-binary-buildpack.git"