name: Deploy Rust Docker to Heroku

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
      - name: Build Docker image
        run: docker build -t registry.heroku.com/standard-rust-axum-api/web .
      - name: Push Docker image
        run: docker push registry.heroku.com/standard-rust-axum-api/web
      - name: Release app on Heroku
        run: heroku container:release web -a standard-rust-axum-api
      - name: Deployment complete
        run: echo "✅ standard-rust-axum-api successfully deployed to Heroku!"
